set_property SRC_FILE_INFO {cfile:D:/SoC/PYNQ-Z2/GPIOInputWithButton/GPIOInputWithButton.srcs/constrs_1/new/GPIOXdc.xdc rfile:../../../GPIOInputWithButton.srcs/constrs_1/new/GPIOXdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {Button_Input_tri_i[0]}]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports {Button_Input_tri_i[1]}]
