set_property SRC_FILE_INFO {cfile:D:/SoC/PYNQ-Z2/RunningLightWithSwitch/RunningLightWithSwitch.srcs/constrs_1/new/GPIOXdc.xdc rfile:../../../RunningLightWithSwitch.srcs/constrs_1/new/GPIOXdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M20 [get_ports {GPIO_INPUT_tri_i[0]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M19 [get_ports {GPIO_INPUT_tri_i[1]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R14 [get_ports {GPIO_OUTPUT_tri_o[0]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN P14 [get_ports {GPIO_OUTPUT_tri_o[1]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN N16 [get_ports {GPIO_OUTPUT_tri_o[2]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {GPIO_OUTPUT_tri_o[3]}]
